<?xml version="1.0" encoding="utf-8"?>
<odoo noupdate="1">
    <record id="order_sync_failure" model="mail.template">
        <field name="name">Shopee: Order Synchronization Failure</field>
        <field name="model_id" ref="base.model_res_users"/>
        <field name="subject">Synchronization of Shopee order {{ ctx.get('shopee_order_ref') }} has failed</field>
        <field name="email_from">{{ (object.company_id.email or object.user_id.email_formatted or user.email_formatted) }}</field>
        <field name="email_to">{{ ctx.get('email_to') }}</field>
        <field name="lang">{{ object.lang }}</field>
        <field name="body_html" type="html">
            <div>
                <p>The synchronization of the Shopee order with reference <t t-out="ctx.get('shopee_order_ref') or ''">REF</t> encountered an error and was not completed.</p>
                <p>Unless the order is cancelled in Shopee, no other synchronization will be attempted.</p>
                <p>To schedule a new synchronization attempt, proceed as follows:
                    <ol>
                        <li>Enter the Developer Tools.</li>
                        <li>Open the form of the Shopee Shop on which the order was placed.</li>
                        <li>Navigate to the Order Follow-up tab.</li>
                        <li>Set a date for <em>Last Order Synchronization Date</em> that is anterior to the last status update of the order.</li>
                        <li>Save the changes and click on the <em>SYNC ORDERS</em> button.</li>
                    </ol>
                </p>
                <p>If the problem persists, contact <a href="https://www.odoo.com/help/">Odoo support</a>.</p>
            </div>
        </field>
    </record>

    <record id="inventory_sync_failure" model="mail.template">
        <field name="name">Shopee: Inventory Synchronization Failure</field>
        <field name="model_id" ref="base.model_res_users"/>
        <field name="subject">Synchronization of Shopee inventory has failed</field>
        <field name="email_from">{{ (object.company_id.email or object.user_id.email_formatted or user.email_formatted) }}</field>
        <field name="email_to">{{ ctx.get('email_to') }}</field>
        <field name="lang">{{ object.lang }}</field>
        <field name="body_html" type="html">
            <style>
                .shopee_table {
                    width: 100%;
                    max-width: 900px;
                    border-collapse: collapse;
                }

                .shopee_table th,
                .shopee_table td {
                    border: 1px solid #888;
                }

                .shopee_table th {
                    white-space: nowrap;
                }

                .shopee_table thead th {
                    padding: 0.5em 0.5em;
                    text-align: center;
                    border-bottom: 1px solid #888;
                }

                .shopee_table tbody th,
                .shopee_table tbody td {
                    padding: 0.5em 0.5em 1em;
                    vertical-align: top;
                }
            </style>
            <div>
                <p>The synchronization of the inventory for Shopee Shop
                    <b><t t-out="ctx.get('shopee_shop') or ''">REF</t></b>
                    encountered some errors and was not completed.</p>
                <p>Here are the errors sent by Shopee: </p>
                <table class="shopee_table">
                    <thead>
                        <tr>
                            <th>Shopee Item Identifier</th>
                            <th>Message</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr t-foreach="ctx.get('error_messages')" t-as="error">
                            <th><t t-out="error['item_identifier']"/></th>
                            <td>
                                <t t-if="error['message']" t-out="error['message']"/>
                                <t t-else="">An unknown error occurred during the synchronisation with Shopee.
                                    Unfortunately you need to manually check if the available quantity for the product is correct or not.
                                    If the problem persists, contact <a href="https://www.odoo.com/help/">Odoo support </a>.
                                </t>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </field>
    </record>

    <record id="picking_sync_failure" model="mail.template">
        <field name="name">Shopee: Shipping Label Synchronization Failure</field>
        <field name="model_id" ref="base.model_res_users"/>
        <field name="subject">Synchronization of shipping labels has failed</field>
        <field name="email_from">{{ (object.company_id.email or object.user_id.email_formatted or user.email_formatted) }}</field>
        <field name="email_to">{{ ctx.get('email_to') }}</field>
        <field name="lang">{{ object.lang }}</field>
        <field name="body_html" type="html">
            <style>
                .shopee_table {
                    width: 100%;
                    max-width: 900px;
                    border-collapse: collapse;
                }

                .shopee_table th,
                .shopee_table td {
                    border: 1px solid #888;
                }

                .shopee_table th {
                    white-space: nowrap;
                }

                .shopee_table thead th {
                    padding: 0.5em 0.5em;
                    text-align: center;
                    border-bottom: 1px solid #888;
                }

                .shopee_table tbody th,
                .shopee_table tbody td {
                    padding: 0.5em 0.5em 1em;
                    vertical-align: top;
                }
            </style>
            <div>
                <p>The synchronization of the Shopee shipping labels encountered some errors and was not completed.</p>
                <p>Please correct the problem before manually synchronizing the pickings again, as no other synchronization will be attempted.</p>
                <p>Here are the errors sent by Shopee: </p>
                <table class="shopee_table">
                    <thead>
                        <tr>
                            <th>Batch Picking References</th>
                            <th>Message</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr t-foreach="ctx.get('error_messages')" t-as="error">
                            <th><t t-out="error['batch_picking_refs']"/></th>
                            <td>
                                <t t-if="error['message']" t-out="error['message']"/>
                                <t t-else="">An unknown error occurred during the synchronisation with Shopee.
                                    Unfortunately you need to manually check if the state of the order is correct or not.
                                    If the problem persists, contact <a href="https://www.odoo.com/help/">Odoo support </a>.
                                </t>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </field>
    </record>
</odoo>
